#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Smooth LLM Proxy

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Smooth LLM Proxy"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Project root
PROJECT_ROOT="/home/mreeves/Projects/Personal/smoothllm"

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start after ${max}s${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready on port $port${NC}"
}

# Check dependencies
check_dependencies() {
    echo "Checking dependencies..."

    if ! command -v go &> /dev/null; then
        echo -e "${RED}Go is not installed${NC}"
        exit 1
    fi
    echo -e "${GREEN}Go: $(go version)${NC}"

    if ! command -v node &> /dev/null; then
        echo -e "${RED}Node.js is not installed${NC}"
        exit 1
    fi
    echo -e "${GREEN}Node.js: $(node --version)${NC}"

    if ! command -v npm &> /dev/null; then
        echo -e "${RED}npm is not installed${NC}"
        exit 1
    fi
    echo -e "${GREEN}npm: $(npm --version)${NC}"
}

# Install frontend dependencies if needed
install_frontend_deps() {
    if [ ! -d "$PROJECT_ROOT/frontend/node_modules" ]; then
        echo "Installing frontend dependencies..."
        cd "$PROJECT_ROOT/frontend" && npm install
    else
        echo "Frontend dependencies already installed"
    fi
}

# ============================================
# START SERVICES
# ============================================

check_dependencies
install_frontend_deps

echo ""
echo "========================================"
echo "Starting Services"
echo "========================================"

# Kill any existing processes on our ports
echo "Cleaning up any existing processes..."
lsof -ti:8080 2>/dev/null | xargs -r kill 2>/dev/null || true
lsof -ti:5173 2>/dev/null | xargs -r kill 2>/dev/null || true
sleep 1

# Backend (Go/Gin)
echo ""
echo "Starting Backend..."
cd "$PROJECT_ROOT/backend" && go run cmd/api/main.go &
BACKEND_PID=$!
wait_for_service 8080 "Backend API"

# Frontend (Vue/Vite)
echo ""
echo "Starting Frontend..."
cd "$PROJECT_ROOT/frontend" && npm run dev &
FRONTEND_PID=$!
wait_for_service 5173 "Frontend Dev Server"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo "  Backend API:  http://localhost:8080"
echo "  Frontend:     http://localhost:5173"
echo ""
echo "Health Check:   http://localhost:8080/health"
echo ""
echo "Process IDs:"
echo "  Backend:  $BACKEND_PID"
echo "  Frontend: $FRONTEND_PID"
echo ""
echo "To stop services:"
echo "  kill $BACKEND_PID $FRONTEND_PID"
echo ""
echo "========================================"

# Keep script running to maintain processes
wait
